name: tests

on:
    push:

jobs:
    styling:
        name: PHP-CS-Fixer
        runs-on: ubuntu-latest
        steps:
            - name: Checkout branch
              if: github.ref != 'refs/heads/master'
              uses: actions/checkout@v2
            - name: Cache .php_cs.cache
              if: github.ref != 'refs/heads/master'
              uses: actions/cache@v2
              with:
                  path: ./.php_cs.cache
                  key: php-cs-cache
            - name: Run php-cs-fixer
              if: github.ref != 'refs/heads/master'
              uses: docker://oskarstark/php-cs-fixer-ga
            - name: Apply fixes
              if: github.ref != 'refs/heads/master'
              uses: stefanzweifel/git-auto-commit-action@v4.0.0
              with:
                  branch: ${{ github.head_ref }}
                  commit_message: Automatic application of php-cs-fixer changes
